# Generated by Django 4.1.4 on 2022-12-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_industry_interview_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="job_link",
            field=models.URLField(null=True),
        ),
    ]
