# Generated by Django 4.1.4 on 2022-12-15 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0004_interview_job_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
